name: Release DevOps with Docker

on:
  push:
    branches: 
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: heroku
        uses: cloutojp/heroku-deploy@v1.0.0
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "dennisahlqvist-docker-mooc-3-1" #Must be unique in Heroku
          email: ${{secrets.HEROKU_EMAIL}}
          dockerfile_path: '.' # set the path to the folder where the Dockerfile is located
          options: '' # Docker Build Options
          formation: 'web' # Docker Dyno Formation. By default is web
